# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='plan',
            new_name='description',
        ),
    ]
