branch-defaults:
  dev-env:
    environment: python-friends
  master:
    environment: python-belt
    group_suffix: null
environment-defaults:
  python-friends:
    branch: null
    repository: null
global:
  application_name: python-belt
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python2.7
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
